name: SlimefunBase64Getter
author: balugaq
description: This is a plugin
main: com.balugaq.sbg.implementation.SlimefunBase64Getter
website: https://github.com/balugaq/SlimefunBase64Getter
version: ${project.version}
api-version: 1.20
